I.	Receipt Table Details:

SELECT * FROM AR_CASH_RECEIPTS_ALL WHERE RECEIPT_NUMBER LIKE 'RECEIPT_663976'
SELECT * FROM AR_CASH_RECEIPT_HISTORY_ALL WHERE CASH_RECEIPT_ID = '109991'
SELECT * FROM AR_RECEIVABLE_APPLICATIONS_ALL WHERE CASH_RECEIPT_ID = '109991'
SELECT * FROM AR_PAYMENT_SCHEDULES_ALL WHERE CASH_RECEIPT_ID = '109991' REMAINING AMOUNT WE YOU CAN ABLE TO SEE 
SELECT EVENT_ID FROM AR_CASH_RECEIPT_HISTORY_ALL WHERE CASH_RECEIPT_ID = '109991'

  II.	Sub Ledger Journal Details : 

SELECT * FROM XLA_EVENTS WHERE EVENT_ID ='3318731';
SELECT * FROM  XLA_AE_HEADERS WHERE EVENT_ID  ='3318731';

We can see these details only after create accounting program completed. 
  
SELECT * FROM XLA_AE_LINES WHERE AE_HEADER_ID = '4945977';
SELECT * FROM GL_INTERFACE WHERE REFERENCE26 = '3318731'

III.	GL Ledger: 
SELECT * FROM GL_JE_BATCHES WHERE NAME = 'Receivable A 1546007 ';
SELECT * FROM GL_JE_HEADERS WHERE JE_BATCH_ID = '2927184';
SELECT * FROM GL_JE_LINES WHERE HE_HEADER_ID = '' Status U It means data not posted. 
